// Generated by CoffeeScript 2.0.1
var basename, bookDir, booknames, extname, f, fs, join, load, resolve;

fs = require('fs');

({extname, basename, resolve, join} = require('path'));

bookDir = resolve(__dirname, '../color-books');

booknames = (function() {
  var i, len, ref, results;
  ref = fs.readdirSync(bookDir);
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    f = ref[i];
    if (extname(f) === '.json') {
      results.push(basename(f, '.json'));
    }
  }
  return results;
})();

load = function(bookname) {
  return require(join(bookDir, `${bookname}.json`));
};

module.exports = {booknames, load};
